package assembly

// customattr.go — a thin, reader-layer accessor over the CustomAttribute table
// (tCustomAttribute = 0x0C, §II.22.10). The table is parsed and its rows retained by
// metadata.go; this file only enumerates them and answers the two questions the
// first-party semantic layer needs: is an element compiler-generated, and is a method
// an extension method. It is byte-parsing only — nothing is loaded or executed.
//
// A CustomAttribute row is three columns (tableSchemas[tCustomAttribute]):
//
//	[0] Parent — HasCustomAttribute coded index: the annotated element (TypeDef/MethodDef/…)
//	[1] Type   — CustomAttributeType coded index: the attribute's ctor (MethodDef | MemberRef)
//	[2] Value  — a #Blob of the ctor arguments (not decoded here)
//
// The attribute's *type* (e.g. "System.Runtime.CompilerServices.ExtensionAttribute") is
// the ctor's owning type, resolved through the existing coded-index machinery.

import "strings"

// well-known attribute type short names (the matched suffix; namespace-independent so a
// MemberRef parent named with or without its namespace both hit).
const (
	attrCompilerGenerated = "CompilerGeneratedAttribute"
	attrGeneratedCode     = "GeneratedCodeAttribute"
	attrExtension         = "ExtensionAttribute"
)

// customAttrCtors returns the attribute-ctor tokens (the Type column, a MethodDef or
// MemberRef) of every CustomAttribute row whose Parent is the given element token. The
// caller passes a TypeDef or MethodDef token (td.Token / m.Token).
func (a *Assembly) customAttrCtors(parent Token) []Token {
	if a.md == nil {
		return nil
	}
	var out []Token
	for _, row := range a.md.rows[tCustomAttribute] {
		if len(row) < 2 {
			continue
		}
		if decodeCoded(ciHasCustomAttribute, row[0]) == parent {
			out = append(out, decodeCoded(ciCustomAttributeType, row[1]))
		}
	}
	return out
}

// attributeTypeName resolves an attribute-ctor token to the display name of the
// attribute type it constructs. A MemberRef ctor names its parent type directly; a
// MethodDef ctor (an attribute type defined in this assembly) is resolved to its owning
// TypeDef. An unresolvable token yields "".
func (a *Assembly) attributeTypeName(ctor Token) string {
	switch ctor.Table() {
	case tMemberRef:
		if mr := a.MemberRef(ctor.RID()); mr != nil {
			return mr.Type // parent type display "Namespace.Name"
		}
	case tMethodDef:
		return a.owningTypeDisplay(ctor.RID())
	}
	return ""
}

// owningTypeDisplay finds the display name of the type that declares a given MethodDef
// RID, by scanning the declared types' method lists. Used only for the rare in-assembly
// attribute-type ctor; the hot path is a MemberRef.
func (a *Assembly) owningTypeDisplay(methodRID uint32) string {
	for i := range a.Types {
		for _, m := range a.Types[i].Methods {
			if m != nil && m.RID == methodRID {
				return typeDisplay(TypeRef{Namespace: a.Types[i].Namespace, Name: a.Types[i].Name})
			}
		}
	}
	return ""
}

// hasAttributeSuffix reports whether the element carries a custom attribute whose type
// name ends with any of the given short names (so "…CompilerServices.ExtensionAttribute"
// and a bare "ExtensionAttribute" both match). Matching on the observable attribute type
// is the whole point: it never keys on a method/type *name* substring.
func (a *Assembly) hasAttributeSuffix(parent Token, suffixes ...string) bool {
	for _, ctor := range a.customAttrCtors(parent) {
		name := a.attributeTypeName(ctor)
		for _, sfx := range suffixes {
			if name == sfx || strings.HasSuffix(name, "."+sfx) {
				return true
			}
		}
	}
	return false
}

// isCompilerGenerated reports whether an element (TypeDef or MethodDef token) carries
// [CompilerGenerated] or [GeneratedCode] — the two attributes that mark a symbol as
// compiler/codegen-synthesized (§4.3(8), SYMBOLS.md).
func (a *Assembly) isCompilerGenerated(parent Token) bool {
	return a.hasAttributeSuffix(parent, attrCompilerGenerated, attrGeneratedCode)
}

// IsCompilerGeneratedType reports whether a type is compiler-generated by its attributes
// OR its mangled name (e.g. "<FetchAsync>d__0", "<>c"). Exported for the first-party
// production pass and its tests.
func (a *Assembly) IsCompilerGeneratedType(td *TypeDef) bool {
	if td == nil {
		return false
	}
	if a.isCompilerGenerated(td.Token) {
		return true
	}
	_, _, ok := decodeMangled(td.Name)
	return ok
}

// IsExtensionMethod reports whether a method is a C# extension method: it carries
// [Extension] and is static (the compiler emits [Extension] only for a method with a
// leading `this` parameter). The discriminator is the observable attribute, so a static
// method of the same shape WITHOUT [Extension] is correctly not an extension method.
func (a *Assembly) IsExtensionMethod(m *MethodDef) bool {
	if m == nil {
		return false
	}
	if m.Flags&0x0010 == 0 { // MethodAttributes.Static
		return false
	}
	return a.hasAttributeSuffix(m.Token, attrExtension)
}
