package goanalysis

import (
	"context"
	"fmt"
	"path"
	"strings"

	"github.com/ferralon-ai/ferralon-assay/plugin"
)

// sinkSymbol is the package+symbol decomposition of a sink SCIP id.
type sinkSymbol struct {
	pkgPath  string // import path of the sink's package
	pkgName  string // last path element (the default import identifier)
	receiver string // method receiver type name, empty for package-level funcs
	name     string // function/method name
}

// GenerateHarness emits a runnable reproducer SKELETON (Go source text) that
// imports the sink symbol's package and calls the sink, with a clearly-marked
// TODO for the attacker-controlled input. It does NOT trigger the vuln — it is a
// structural skeleton, declared as such (Skeleton=true, Partial).
//
// Partiality is declared, never overclaimed (inv.5): an unparseable sink SCIP, an
// unknown input shape, and the fact that this is a skeleton rather than a working
// exploit are all carried as Partial with a reason — never the retired
// unsupported_phase1 code, and never a confident "exploit" claim.
func GenerateHarness(_ context.Context, req plugin.GenerateHarnessRequest) (plugin.HarnessResult, error) {
	sym, ok := parseSinkSCIP(req.Sink)
	if !ok {
		return plugin.HarnessResult{
			Partiality: plugin.Partial(plugin.PartialReasonToolFailure),
			Skeleton:   true,
		}, nil
	}

	kind := req.Kind
	if kind == "" {
		kind = "unit"
	}

	src := renderHarness(sym, req.Ingress, kind)

	// The input shape is unknown (we cannot construct attacker-controlled values),
	// so the harness is a skeleton, not a working exploit: declared Partial.
	reasons := []string{plugin.PartialReasonDynamicDispatch}
	if kind != "unit" && kind != "fuzz" && kind != "integration" {
		reasons = append(reasons, plugin.PartialReasonToolFailure)
	}

	return plugin.HarnessResult{
		Partiality: plugin.Partial(reasons...),
		Source:     src,
		Skeleton:   true,
	}, nil
}

// parseSinkSCIP decomposes a SCIP id of the emitter's grammar
//
//	scip-go gomod <module> <version> <pkgPath>/<descriptor>
//
// where <descriptor> is "<name>()." for a func or "<recv>#<name>()." for a
// method. Anything not matching this shape is unparseable (ok=false).
func parseSinkSCIP(scip string) (sinkSymbol, bool) {
	fields := strings.Fields(scip)
	if len(fields) < 5 || fields[0] != "scip-go" || fields[1] != "gomod" {
		return sinkSymbol{}, false
	}
	desc := fields[4]
	slash := strings.LastIndex(desc, "/")
	if slash < 0 {
		return sinkSymbol{}, false
	}
	pkgPath := desc[:slash]
	tail := strings.TrimSuffix(desc[slash+1:], "().")
	if tail == "" || tail == desc[slash+1:] { // missing the "()." func/method suffix
		return sinkSymbol{}, false
	}

	sym := sinkSymbol{pkgPath: pkgPath, pkgName: path.Base(pkgPath)}
	if h := strings.IndexByte(tail, '#'); h >= 0 {
		sym.receiver = tail[:h]
		sym.name = tail[h+1:]
	} else {
		sym.name = tail
	}
	if sym.name == "" || sym.pkgPath == "" {
		return sinkSymbol{}, false
	}
	return sym, true
}

// renderHarness produces the Go source skeleton. For a method sink it constructs
// a zero-value receiver and calls the method; for a package-level func it calls
// the func directly. Attacker-controlled input is left as a TODO.
func renderHarness(sym sinkSymbol, ingress, kind string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by tegron-plugin-go (harness skeleton). DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// This is a reproducer SKELETON for sink %s.%s — it calls the sink but\n", sym.pkgName, sym.name)
	fmt.Fprintf(&b, "// does NOT supply attacker-controlled input and does NOT prove exploitability.\n")
	fmt.Fprintf(&b, "// kind=%s", kind)
	if ingress != "" {
		fmt.Fprintf(&b, " ingress=%s", ingress)
	}
	b.WriteString("\npackage harness\n\n")
	fmt.Fprintf(&b, "import (\n\t\"testing\"\n\n\t%q\n)\n\n", sym.pkgPath)

	call := sym.callExpr()
	switch kind {
	case "fuzz":
		fmt.Fprintf(&b, "func FuzzSink(f *testing.F) {\n")
		fmt.Fprintf(&b, "\tf.Fuzz(func(t *testing.T, in string) {\n")
		fmt.Fprintf(&b, "\t\t// TODO: shape the fuzz input into the attacker-controlled value the sink consumes.\n")
		fmt.Fprintf(&b, "\t\t%s\n", call)
		fmt.Fprintf(&b, "\t})\n}\n")
	default: // unit | integration
		fmt.Fprintf(&b, "func TestSinkReachable(t *testing.T) {\n")
		fmt.Fprintf(&b, "\t// TODO: replace with the attacker-controlled input that triggers the vulnerability.\n")
		fmt.Fprintf(&b, "\t%s\n", call)
		fmt.Fprintf(&b, "}\n")
	}
	return b.String()
}

// callExpr renders the call to the sink. Methods are invoked on a zero-value
// receiver of the receiver type; package-level funcs are called directly. The
// argument is a TODO placeholder rather than a real attacker-controlled value.
func (s sinkSymbol) callExpr() string {
	if s.receiver != "" {
		return fmt.Sprintf("var recv %s.%s\n\t_ = recv.%s(/* TODO: attacker-controlled input */)", s.pkgName, s.receiver, s.name)
	}
	return fmt.Sprintf("_ = %s.%s(/* TODO: attacker-controlled input */)", s.pkgName, s.name)
}
