package jsanalysis

import (
	"context"
	"fmt"
	"strings"

	"github.com/ferralon-ai/ferralon-assay/plugin"
)

// sinkSymbol is the module + enclosing-class + name decomposition of a JS/TS sink
// SCIP id, as emitted by scipSymbol (see scip.go). module is the source file path
// relative to the build root ('/'-joined, extension stripped); enclosing is the
// chain of enclosing class names (empty for a module-level function); name is the
// function/method identifier.
type sinkSymbol struct {
	module    string
	enclosing []string
	name      string
}

// GenerateHarness emits a runnable Node reproducer SKELETON (JavaScript source
// text) that require()s the sink symbol's module and calls the sink, with a
// clearly-marked TODO for the attacker-controlled input. It does NOT trigger the
// vuln — it is a structural skeleton, declared as such (Skeleton=true, Partial).
//
// Partiality is declared, never overclaimed (inv.5): an unparseable sink SCIP, the
// fact that the attacker-controlled input shape is unknown, and the fact that this
// is a skeleton rather than a working exploit are all carried as Partial with a
// reason — never the retired unsupported_phase1 code, and never a confident
// "exploit" claim. An unparseable sink yields a Partial(tool_failure) skeleton.
func GenerateHarness(_ context.Context, req plugin.GenerateHarnessRequest) (plugin.HarnessResult, error) {
	sym, ok := parseSinkSCIP(req.Sink)
	if !ok {
		return plugin.HarnessResult{
			Partiality: plugin.Partial(plugin.PartialReasonToolFailure),
			Skeleton:   true,
		}, nil
	}

	kind := req.Kind
	if kind == "" {
		kind = "unit"
	}

	src := renderHarness(sym, req.Ingress, kind)

	// The input shape is unknown (we cannot construct attacker-controlled values)
	// and JS dispatch is not type-resolved, so the harness is a skeleton, not a
	// working exploit: declared Partial.
	reasons := []string{plugin.PartialReasonDynamicDispatch}
	if kind != "unit" && kind != "fuzz" && kind != "integration" {
		reasons = append(reasons, plugin.PartialReasonToolFailure)
	}

	return plugin.HarnessResult{
		Partiality: plugin.Partial(reasons...),
		Source:     src,
		Skeleton:   true,
	}, nil
}

// parseSinkSCIP decomposes a SCIP id of the emitter's grammar (see scip.go):
//
//	scip-typescript npm <package> <version> <descriptors>
//
// where <descriptors> is moduleDescriptor + enclosing-type chain + final
// descriptor, e.g. "src/util/Foo#bar(2)." for method Foo.bar in module src/util,
// or "src/util/handler()." for the module-level func handler. A bare type
// descriptor ("src/util/Foo#") is not callable and is treated as unparseable.
// Anything not matching this shape is unparseable (ok=false).
func parseSinkSCIP(scip string) (sinkSymbol, bool) {
	fields := strings.Fields(scip)
	if len(fields) < 5 || fields[0] != "scip-typescript" || fields[1] != "npm" {
		return sinkSymbol{}, false
	}
	desc := fields[4]
	// A callable descriptor ends with ")." — a bare type ("Foo#") does not.
	if !strings.HasSuffix(desc, ").") {
		return sinkSymbol{}, false
	}

	var sym sinkSymbol
	var tail string // the final "name(arity)." descriptor
	if h := strings.LastIndex(desc, "#"); h >= 0 {
		head := desc[:h] // "module/Type1#Type2#...#TypeN"
		tail = desc[h+1:]
		parts := strings.Split(head, "#") // ["module/Type1", "Type2", ...]
		first := parts[0]
		slash := strings.LastIndex(first, "/")
		if slash < 0 {
			return sinkSymbol{}, false // no module/ prefix: malformed
		}
		sym.module = first[:slash]
		sym.enclosing = append([]string{first[slash+1:]}, parts[1:]...)
	} else {
		slash := strings.LastIndex(desc, "/")
		if slash < 0 {
			return sinkSymbol{}, false // no module/ prefix: malformed
		}
		sym.module = desc[:slash]
		tail = desc[slash+1:]
	}

	open := strings.IndexByte(tail, '(')
	if open <= 0 { // no name, or "(" at position 0
		return sinkSymbol{}, false
	}
	sym.name = tail[:open]
	if sym.module == "" {
		return sinkSymbol{}, false
	}
	return sym, true
}

// renderHarness produces the Node/CommonJS source skeleton. For a method sink it
// constructs the enclosing class and calls the method; for a module-level func it
// calls the export directly. Attacker-controlled input is left as a TODO. CommonJS
// require() is used for the broadest Node compatibility.
func renderHarness(sym sinkSymbol, ingress, kind string) string {
	local := sym.localName()
	var b strings.Builder
	b.WriteString("// Code generated by tegron-plugin-js (harness skeleton). DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// This is a reproducer SKELETON for sink %s.%s — it calls the sink but\n", local, sym.name)
	b.WriteString("// does NOT supply attacker-controlled input and does NOT prove exploitability.\n")
	fmt.Fprintf(&b, "// kind=%s", kind)
	if ingress != "" {
		fmt.Fprintf(&b, " ingress=%s", ingress)
	}
	b.WriteByte('\n')
	fmt.Fprintf(&b, "\nconst %s = require(%q);\n\n", local, sym.requireSpecifier())

	switch kind {
	case "fuzz":
		b.WriteString("// jsfuzz-compatible entry: `jsfuzz <this-file>` calls fuzz(buf) with random input.\n")
		b.WriteString("module.exports.fuzz = function (buf) {\n")
		b.WriteString("\t// TODO: shape the fuzz input (buf) into the attacker-controlled value the sink consumes.\n")
		writeCall(&b, sym, local, "\t")
		b.WriteString("};\n")
	default: // unit | integration
		b.WriteString("const test = require(\"node:test\");\n\n")
		b.WriteString("test(\"sink reachable\", () => {\n")
		b.WriteString("\t// TODO: replace with the attacker-controlled input that triggers the vulnerability.\n")
		writeCall(&b, sym, local, "\t")
		b.WriteString("});\n")
	}
	return b.String()
}

// writeCall writes the sink call statement(s) at the given indent. A method sink is
// invoked on a freshly-constructed enclosing class; a module-level func is called
// directly on the required module. The argument is a TODO placeholder rather than a
// real attacker-controlled value.
func writeCall(b *strings.Builder, sym sinkSymbol, local, indent string) {
	const todo = "/* TODO: attacker-controlled input */"
	if len(sym.enclosing) > 0 {
		fmt.Fprintf(b, "%sconst recv = new %s.%s();\n", indent, local, sym.enclosing[0])
		fmt.Fprintf(b, "%srecv.%s(%s);\n", indent, sym.name, todo)
		return
	}
	fmt.Fprintf(b, "%s%s.%s(%s);\n", indent, local, sym.name, todo)
}

// requireSpecifier is the CommonJS module specifier for the sink's module. A module
// declared at the build root ("_root_" or empty) requires the package entry (".");
// any other module requires the relative source path.
func (s sinkSymbol) requireSpecifier() string {
	if s.module == "" || s.module == "_root_" {
		return "."
	}
	return "./" + s.module
}

// localName is the JavaScript identifier the skeleton binds the required module to.
// It is the module's base path element sanitized to a valid identifier, defaulting
// to "sink" when nothing usable remains.
func (s sinkSymbol) localName() string {
	base := s.module
	if i := strings.LastIndex(base, "/"); i >= 0 {
		base = base[i+1:]
	}
	base = sanitizeIdent(base)
	if base == "" {
		return "sink"
	}
	return base
}

// sanitizeIdent maps an arbitrary string to a valid JS identifier: non-identifier
// runes become '_', and a leading digit is prefixed with '_'.
func sanitizeIdent(s string) string {
	var b strings.Builder
	for i, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r == '_', r == '$':
			b.WriteRune(r)
		case r >= '0' && r <= '9':
			if i == 0 {
				b.WriteByte('_')
			}
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}
