package jsanalysis

import (
	"context"
	"os"
	"path/filepath"
	"testing"

	"github.com/ferralon-ai/ferralon-assay/plugin"
)

// writeLockTree writes files (path→content, relative to a fresh temp dir) and returns the
// dir. A trivial .js file is always added so the tree is a recognizable JS source tree
// (loadProgram is not exercised here, but it keeps the fixtures realistic).
func writeLockTree(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	files["src/index.js"] = "'use strict';\nfunction main() {}\n"
	for rel, content := range files {
		full := filepath.Join(dir, rel)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return dir
}

func resolveJS(t *testing.T, dir, coord string) plugin.DependencyVersionResult {
	t.Helper()
	res, err := ResolveDependencyVersions(context.Background(), plugin.ResolveVersionsRequest{BuildDir: dir, Coordinate: coord})
	if err != nil {
		t.Fatalf("ResolveDependencyVersions: %v", err)
	}
	return res
}

func mustMatch(t *testing.T, res plugin.DependencyVersionResult, wantVer string) {
	t.Helper()
	if !res.Found {
		t.Fatalf("coordinate not found; all=%+v", res.All)
	}
	if !res.Match.Resolved {
		t.Fatalf("match UNRESOLVED, want resolved %q; match=%+v", wantVer, res.Match)
	}
	if res.Match.Version != wantVer {
		t.Fatalf("version = %q, want %q", res.Match.Version, wantVer)
	}
}

// --- package-lock.json -------------------------------------------------------

const packageLockV3 = `{
  "name": "app",
  "lockfileVersion": 3,
  "requires": true,
  "packages": {
    "": { "name": "app", "version": "1.0.0" },
    "node_modules/left-pad": { "version": "1.3.0" },
    "node_modules/express": { "version": "4.18.2" },
    "node_modules/express/node_modules/cookie": { "version": "0.5.0" }
  }
}`

const packageLockV2 = `{
  "name": "app",
  "lockfileVersion": 2,
  "packages": {
    "": { "name": "app", "version": "1.0.0" },
    "node_modules/left-pad": { "version": "1.4.0" }
  },
  "dependencies": {
    "left-pad": { "version": "1.4.0" }
  }
}`

const packageLockV1 = `{
  "name": "app",
  "lockfileVersion": 1,
  "dependencies": {
    "left-pad": { "version": "1.2.0" },
    "express": {
      "version": "4.17.1",
      "dependencies": {
        "cookie": { "version": "0.4.0" }
      }
    }
  }
}`

func TestPackageLock_V3_PackagesMap(t *testing.T) {
	dir := writeLockTree(t, map[string]string{"package-lock.json": packageLockV3})
	mustMatch(t, resolveJS(t, dir, "left-pad"), "1.3.0")
	mustMatch(t, resolveJS(t, dir, "express"), "4.18.2")
	// nested transitive (the express-scoped cookie) is also resolved
	mustMatch(t, resolveJS(t, dir, "cookie"), "0.5.0")
}

func TestPackageLock_V2_PreferPackagesMap(t *testing.T) {
	dir := writeLockTree(t, map[string]string{"package-lock.json": packageLockV2})
	mustMatch(t, resolveJS(t, dir, "left-pad"), "1.4.0")
}

func TestPackageLock_V1_DependenciesMap(t *testing.T) {
	dir := writeLockTree(t, map[string]string{"package-lock.json": packageLockV1})
	mustMatch(t, resolveJS(t, dir, "left-pad"), "1.2.0")
	mustMatch(t, resolveJS(t, dir, "express"), "4.17.1")
	mustMatch(t, resolveJS(t, dir, "cookie"), "0.4.0") // nested v1 transitive
}

func TestPackageLock_RootPackageNotADependency(t *testing.T) {
	dir := writeLockTree(t, map[string]string{"package-lock.json": packageLockV3})
	res := resolveJS(t, dir, "app")
	if res.Found {
		t.Fatalf("root package 'app' must not be reported as a dependency; got %+v", res.Match)
	}
}

func TestPackageLock_Unparseable_IsPartial(t *testing.T) {
	dir := writeLockTree(t, map[string]string{"package-lock.json": "{ not valid json"})
	res := resolveJS(t, dir, "left-pad")
	if res.Partiality.Complete {
		t.Fatal("unparseable lockfile must degrade to declared-partial")
	}
	if res.Found {
		t.Fatalf("nothing should resolve from an unparseable lockfile; got %+v", res.Match)
	}
}

// --- yarn.lock ---------------------------------------------------------------

const yarnClassic = `# THIS IS AN AUTOGENERATED FILE.
# yarn lockfile v1


left-pad@^1.3.0:
  version "1.3.0"
  resolved "https://registry.yarnpkg.com/left-pad/-/left-pad-1.3.0.tgz"
  integrity sha512-xxx

"@scope/pkg@^2.0.0":
  version "2.1.0"
  resolved "https://registry.yarnpkg.com/@scope/pkg/-/pkg-2.1.0.tgz"

express@^4.0.0, express@^4.18.0:
  version "4.18.2"
`

const yarnBerry = `# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

__metadata:
  version: 6
  cacheKey: 8

"left-pad@npm:^1.3.0":
  version: 1.3.0
  resolution: "left-pad@npm:1.3.0"
  checksum: abc

"@scope/pkg@npm:^2.0.0":
  version: 2.1.0
  resolution: "@scope/pkg@npm:2.1.0"
`

func TestYarnLock_Classic(t *testing.T) {
	dir := writeLockTree(t, map[string]string{"yarn.lock": yarnClassic})
	mustMatch(t, resolveJS(t, dir, "left-pad"), "1.3.0")
	mustMatch(t, resolveJS(t, dir, "@scope/pkg"), "2.1.0")
	mustMatch(t, resolveJS(t, dir, "express"), "4.18.2") // multi-descriptor header
}

func TestYarnLock_Berry(t *testing.T) {
	dir := writeLockTree(t, map[string]string{"yarn.lock": yarnBerry})
	mustMatch(t, resolveJS(t, dir, "left-pad"), "1.3.0")
	mustMatch(t, resolveJS(t, dir, "@scope/pkg"), "2.1.0")
	// __metadata is not a package entry
	if res := resolveJS(t, dir, "__metadata"); res.Found {
		t.Fatalf("__metadata must not be a resolved dependency; got %+v", res.Match)
	}
}

func TestYarnLock_NoVersionLine_IsUnresolved(t *testing.T) {
	const noVer = `broken@^1.0.0:
  resolved "https://example.com/broken.tgz"
`
	dir := writeLockTree(t, map[string]string{"yarn.lock": noVer})
	res := resolveJS(t, dir, "broken")
	if !res.Found {
		t.Fatal("the entry should be FOUND (declared) even without a version")
	}
	if res.Match.Resolved {
		t.Fatalf("a yarn entry with no version line must be UNRESOLVED; got %+v", res.Match)
	}
}

// --- pnpm-lock.yaml ----------------------------------------------------------

const pnpmV6 = `lockfileVersion: '6.0'

dependencies:
  left-pad:
    specifier: ^1.3.0
    version: 1.3.0

packages:

  /left-pad@1.3.0:
    resolution: {integrity: sha512-xxx}
    dev: false

  /@scope/pkg@2.1.0:
    resolution: {integrity: sha512-yyy}
    dev: false

  /react-dom@18.2.0(react@18.2.0):
    resolution: {integrity: sha512-zzz}
    dev: false
`

const pnpmV5 = `lockfileVersion: 5.4

packages:

  /left-pad/1.2.0:
    resolution: {integrity: sha512-xxx}
    dev: false

  /@scope/pkg/2.0.0:
    resolution: {integrity: sha512-yyy}
    dev: false
`

func TestPnpmLock_V6_AtSeparator(t *testing.T) {
	dir := writeLockTree(t, map[string]string{"pnpm-lock.yaml": pnpmV6})
	mustMatch(t, resolveJS(t, dir, "left-pad"), "1.3.0")
	mustMatch(t, resolveJS(t, dir, "@scope/pkg"), "2.1.0")
	mustMatch(t, resolveJS(t, dir, "react-dom"), "18.2.0") // peer suffix trimmed
}

func TestPnpmLock_V5_SlashSeparator(t *testing.T) {
	dir := writeLockTree(t, map[string]string{"pnpm-lock.yaml": pnpmV5})
	mustMatch(t, resolveJS(t, dir, "left-pad"), "1.2.0")
	mustMatch(t, resolveJS(t, dir, "@scope/pkg"), "2.0.0")
}

func TestPnpmLock_OnlyPackagesBlockRead(t *testing.T) {
	dir := writeLockTree(t, map[string]string{"pnpm-lock.yaml": pnpmV6})
	// "left-pad" under the top-level dependencies: block carries a version field but is
	// NOT in the packages: block; only the packages: entry is the authoritative resolution.
	res := resolveJS(t, dir, "left-pad")
	mustMatch(t, res, "1.3.0")
	if len(res.All) == 0 {
		t.Fatal("expected resolved packages")
	}
}

// --- no lockfile: declared-partial degrade, never a hard error ---------------

// express@4.x's shape: a real package.json, no committed lockfile.
const packageJSONNoLock = `{
  "name": "express",
  "version": "4.18.2",
  "dependencies": { "cookie": "0.5.0", "qs": "6.11.0" },
  "devDependencies": { "mocha": "^10.0.0" },
  "optionalDependencies": { "fsevents": "^2.3.2" },
  "peerDependencies": { "react": ">=16" }
}`

func TestResolveVersions_NoLockfileDegradesToNoManifest(t *testing.T) {
	dir := writeLockTree(t, map[string]string{"package.json": packageJSONNoLock})
	res := resolveJS(t, dir, "cookie") // resolveJS t.Fatals on a hard error

	if res.Partiality.Complete {
		t.Fatal("a no-lockfile result must be declared-partial, not Complete — it must be distinguishable from a clean scan")
	}
	if !hasReason(res.Partiality, plugin.PartialReasonNoManifest) {
		t.Fatalf("Reasons = %v, want %q", res.Partiality.Reasons, plugin.PartialReasonNoManifest)
	}
}

// The soundness shape: the requested coordinate is PRESENT-but-UNRESOLVED, never absent.
// Found=false here would let the disqualification predicate read "no dependency" and
// fabricate a not-affected.
func TestResolveVersions_NoLockfileSeedsUnresolvedMatch(t *testing.T) {
	dir := writeLockTree(t, map[string]string{"package.json": packageJSONNoLock})
	res := resolveJS(t, dir, "cookie")

	if !res.Found {
		t.Fatalf("declared coordinate must be Found (present-but-unresolved); all=%+v", res.All)
	}
	if res.Match.Resolved {
		t.Fatalf("declared coordinate must be UNRESOLVED (no version source); match=%+v", res.Match)
	}
	if res.Match.Version != "" {
		t.Fatalf("Version = %q, want empty — the declared range must never be reported as an installed version", res.Match.Version)
	}
	if res.Match.Coordinate != "cookie" {
		t.Fatalf("Coordinate = %q, want %q", res.Match.Coordinate, "cookie")
	}
}

func TestResolveVersions_NoLockfileSeedsAllDeclaredFields(t *testing.T) {
	dir := writeLockTree(t, map[string]string{"package.json": packageJSONNoLock})
	res := resolveJS(t, dir, "")

	got := make(map[string]bool, len(res.All))
	for _, d := range res.All {
		if d.Resolved {
			t.Fatalf("seeded dependency %q must be UNRESOLVED; got %+v", d.Coordinate, d)
		}
		got[d.Coordinate] = true
	}
	for _, want := range []string{"cookie", "qs", "mocha", "fsevents", "react"} {
		if !got[want] {
			t.Fatalf("declared dependency %q missing from All=%v", want, got)
		}
	}
}

// A coordinate declared nowhere stays Found=false — the degrade widens nothing beyond
// what package.json actually declares.
func TestResolveVersions_NoLockfileUndeclaredCoordinateNotFound(t *testing.T) {
	dir := writeLockTree(t, map[string]string{"package.json": packageJSONNoLock})
	res := resolveJS(t, dir, "left-pad")
	if res.Found {
		t.Fatalf("an undeclared coordinate must stay Found=false; got %+v", res.Match)
	}
	if !hasReason(res.Partiality, plugin.PartialReasonNoManifest) {
		t.Fatal("the result is still declared-partial: the predicate must not treat this absence as proof")
	}
}

// Neither lockfile nor package.json: empty All, but STILL declared-partial. The partiality
// is the only thing standing between this and a clean-looking scan.
func TestResolveVersions_NoLockfileNoPackageJSONStillPartial(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "index.js"), []byte("x"), 0o644); err != nil {
		t.Fatal(err)
	}
	res := resolveJS(t, dir, "left-pad")
	if res.Partiality.Complete {
		t.Fatal("no lockfile and no package.json must never report Complete")
	}
	if !hasReason(res.Partiality, plugin.PartialReasonNoManifest) {
		t.Fatalf("Reasons = %v, want %q", res.Partiality.Reasons, plugin.PartialReasonNoManifest)
	}
	if len(res.All) != 0 {
		t.Fatalf("nothing is declared, so nothing may be seeded; All=%+v", res.All)
	}
}

// node_modules must not seed: a vendored install's package.json is not the project's
// declaration.
func TestResolveVersions_NoLockfileSkipsNodeModules(t *testing.T) {
	dir := writeLockTree(t, map[string]string{
		"package.json":                       packageJSONNoLock,
		"node_modules/vendored/package.json": `{"name":"vendored","dependencies":{"lodash":"1.0.0"}}`,
	})
	res := resolveJS(t, dir, "lodash")
	if res.Found {
		t.Fatalf("a node_modules package.json must not seed coordinates; got %+v", res.Match)
	}
}

// A present lockfile still wins: the degrade never fires when there is a real
// installed-version source.
func TestResolveVersions_LockfilePresentIgnoresDeclared(t *testing.T) {
	dir := writeLockTree(t, map[string]string{
		"package.json":      packageJSONNoLock,
		"package-lock.json": packageLockV3,
	})
	res := resolveJS(t, dir, "express")
	mustMatch(t, res, "4.18.2")
	if !res.Partiality.Complete {
		t.Fatalf("a clean lockfile parse must stay Complete; reasons=%v", res.Partiality.Reasons)
	}
	for _, d := range res.All {
		if d.Coordinate == "mocha" {
			t.Fatal("declared-only deps must not be seeded when a lockfile exists")
		}
	}
}

// --- hard errors -------------------------------------------------------------

func TestResolveVersions_MissingBuildDirIsHardError(t *testing.T) {
	_, err := ResolveDependencyVersions(context.Background(), plugin.ResolveVersionsRequest{
		BuildDir:   filepath.Join(t.TempDir(), "nope"),
		Coordinate: "left-pad",
	})
	if err == nil {
		t.Fatal("a missing build dir must be a hard error")
	}
}

func TestResolveVersions_CoordinateNotDeclaredNotFound(t *testing.T) {
	dir := writeLockTree(t, map[string]string{"package-lock.json": packageLockV3})
	res := resolveJS(t, dir, "nonexistent-pkg")
	if res.Found {
		t.Fatalf("an undeclared coordinate must be Found=false; got %+v", res.Match)
	}
	if !res.Partiality.Complete {
		t.Fatal("a clean parse with a missing coordinate is still Complete (the absence is known)")
	}
}
