// Package selfdesc holds the tool's self-description drift tests: the layer that
// checks what the binary SAYS about itself against what the code actually IS.
//
// It contains no production code. Every other package in this tree is tested for
// behaviour; this one is tested for honesty, and the two are different failures.
// A scan that computes the right verdict and then stamps the wrong analyzer
// version on it, or prints an uninstall instruction naming a ref it never wrote,
// is wrong in a way no behavioural test can see — both halves work, and only
// their agreement is broken.
//
// # These are drift tests, not golden snapshots
//
// Nothing here freezes a string. Every expected value is COMPUTED from the single
// source of truth (brand.Name, brand.RefNamespace, statestore.DefaultRef, and the
// -X brand.Version stamp the release actually applies) and every actual value is
// SCRAPED from the artifact a customer sees. The assertion is that the two agree.
//
// A golden file would have the opposite property: it records what the tool says
// today, which is the thing under suspicion, and it is regenerated by whoever
// introduced the next drift. That is how this defect class survived — six
// re-inlined literals, none of them checked against their source, including
// inside the file whose doc comment forbids them:
//
//	No consumer may re-inline one of these strings as a literal. A literal is a
//	site a downstream rebrand silently misses.
//	                                      -- internal/brand/brand_identity.go
//
// # What is here
//
//   - stateref_literal_test.go — hermetic, always on. Parses every non-test Go
//     source in the module and fails any string literal that spells a
//     refs/<namespace>/state other than the one statestore actually writes. No
//     build, no exec, no network; it runs in the default `go test ./...`.
//   - envprefix_literal_test.go — same shape, for brand.EnvPrefix: fails any
//     bare "<PREFIX>_..." string literal spelling the CURRENT prefix, deriving
//     its own matcher from brand.EnvPrefix at test-run time rather than a
//     hardcoded prefix. Legacy TEGRON_/NUCLEON_ literals are untouched — they
//     are deliberate EnvOrLegacy fallbacks, not this defect.
//   - selfdesc_live_test.go — opt-in behind the `live` build tag, matching the
//     tree's other opt-in tests (checkout/git_live_test.go,
//     internal/plugin/goanalysis/reach_toolchain_live_test.go). It builds the CLI
//     the way deploy/assay/publish.sh builds it — same reproducible flags, same
//     -X brand.Version stamp — runs a real scan, and checks the identity on every
//     artifact the scan writes. It is wired into publish.sh as step 2b, so a
//     release cut that misdescribes itself aborts before anything is packaged.
package selfdesc
